server:
  port: 23333
  servlet:
  encoding:
    force: true
    charset: UTF-8
    enabled: true

spring:
  #  Spring Boot 2.4为了提升对Kubernetes的支持 将 spring.profiles 作废了
  #  profiles:
  #    active: dal,web,config,image
  # 替换上面作废的spring.profiels.actice配置参数
  config:
    import: application-web.yml,application-ai.yml
  mvc:
    async:
      request-timeout:

chatBilibili:
  version: 0.1.0