server:
  port: 1999

spring:
  #开放spring完全循环构造引入
  main:
    allow-circular-references: true
  #  Spring Boot 2.4为了提升对Kubernetes的支持 将 spring.profiles 作废了
  #  profiles:
  #    active: dal,web,config,image
  # 替换上面作废的spring.profiels.actice配置参数
  config:
    import: application-web.yml,application-ai.yml
  mvc:
    async:
      request-timeout:

chatBilibili:
  version: 0.1.0